config/routes.rb
ReservationsWeb::Application.routes.draw do

  resources :amenities

  root 'amenities#index'

end

app/models/amenity.rb
class Amenity < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 50 }
  validates :capacity, presence: true, numericality: { only_integer: true }
  validates :description, presence: true, length: { maximum: 505 }
end

app/controllers/amenities_controller.rb
class AmenitiesController < ApplicationController
  def new
    @amenity = Amenity.new
  end

  def create
    @amenity = Amenity.new(amenity_params)
    if @amenity.save
      redirect_to @amenity
    else
      render 'new'
    end
  end

  def show
    @amenity = Amenity.find(params[:id])
  end

  def index
    @amenities = Amenity.all
  end

  def edit
    @amenity = Amenity.find(params[:id])
  end

  def update
    @amenity = Amenity.find(params[:id])

    if @amenity.update(amenity_params)
      redirect_to @amenity
    else
      render 'edit'
    end
  end

  def destroy
    @amenity = Amenity.find(params[:id])
    @amenity.destroy

    redirect_to amenities_path
  end

  private
    def amenity_params
      params.require(:amenity).permit(:name, :capacity, :description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/amenities/_form_amenity.html.erb
<%= form_for @amenity do |f| %>
    <% if @amenity.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@amenity.errors.count, "error") %> Se produjeron los siguientes errores:</h2>
          <ul>
            <% @amenity.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :nombre %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :capacidad %><br>
      <%= f.text_field :capacity %>
    </p>
    <p>
      <%= f.label :descripcion %><br>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.submit value="Guardar Amenity" %>
    </p>
<% end %>

app/views/amenities/edit.html.erb
<h1> Modificar Amenity!!</h1>

<%= render 'form_amenity' %>

<%= link_to 'Volver', amenities_path %>

app/views/amenities/index.html.erb
<h1>Amenities</h1>

<%= link_to 'Nuevo amenity', new_amenity_path %>
<table>
  <tr>
    <th>Nombre</th>
    <th>Capacidad</th>
    <th>Descripción</th>
  </tr>

  <% @amenities.each do |amenity| %>
      <tr>
        <td><%= amenity.name %></td>
        <td><%= amenity.capacity %></td>
        <td><%= truncate(amenity.description, :lenght => 20) %></td>
        <td><%= link_to 'Ver', amenity %></td>
        <td><%= link_to 'Editar', edit_amenity_path(amenity) %></td>
        <td><%= link_to 'Eliminar', amenity_path(amenity),
                        method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
  <% end %>
</table>

app/views/amenities/new.html.erb
<h1> New Amenity!!</h1>

<%= render 'form_amenity' %>

<%= link_to 'Volver', amenities_path %>

app/views/amenities/show.html.erb
<p>
    <strong>Nombre:</strong>
    <%= @amenity.name %>
</p>

<p>
    <strong>Nombre:</strong>
    <%= @amenity.capacity %>
</p>

<p>
    <strong>Descripción:</strong>
    <%= @amenity.description %>
</p>
<%= link_to 'Volver', amenities_path %> | <%= link_to 'Editar', edit_amenity_path(@amenity) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReservationsWeb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>